"""
Regenerate QC_validation_2021_f_max.dat / QC_validation_2023_f_max.dat: pins
f_max to each technology's calibrated F_Mult, since fmin/fmax_perc(_mob) only
bound relative shares, not absolute capacity. 2025 is floored to 2020 where
lower, matching commit 5880468.

Usage: python shared/utilities/scripts/generate_validation_f_max.py
"""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parents[3]))  # repo root

import pandas as pd

from energyscope.models import Model
from shared.utils import run_model

_SNAPSHOT_DIR = Path(__file__).parents[1] / 'ES_Snapshot'

_EPS = 0      # numerical margin added on top of the calibrated F_Mult
_ZERO_THR = 1e-9     # F_Mult below this gets no margin -- stays an exact 0


def _build_base_model(validation_dat: str) -> Model:
    """Same file list as shared/models.py, minus any '*_f_max.dat' file -- avoids
    regenerating from a previous run's already-pinned capacities."""
    return Model([
        ('mod', str(_SNAPSHOT_DIR / 'QC_es_main.mod')),
        ('mod', str(_SNAPSHOT_DIR / 'QC_objective_function.mod')),
        ('dat', str(_SNAPSHOT_DIR / 'QC_data.dat')),
        ('dat', str(_SNAPSHOT_DIR / 'QC_mob_techs_dist_B2D.dat')),
        ('dat', str(_SNAPSHOT_DIR / 'QC_techs_B2D.dat')),
        ('dat', str(_SNAPSHOT_DIR / 'QC_mob_params.dat')),
        ('dat', str(_SNAPSHOT_DIR / validation_dat)),
    ])


def _f_mult(res) -> pd.Series:
    """F_Mult for every technology, including zero (locks out techs with no installed capacity)."""
    df = res.variables['F_Mult'].reset_index()
    idx_col = df.columns[0]
    return df.set_index(idx_col)['F_Mult']


def _write_f_max_file(f_mult: pd.Series, out_path: Path, year: str, note: str = '') -> None:
    f_mult = f_mult.sort_index()

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(
            '# Auto-generated by shared/utilities/scripts/generate_validation_f_max.py\n'
            f'# f_max pinned to the installed capacity (F_Mult) computed by the {year} '
            f'validation snapshot run, plus a {_EPS} margin for numerical feasibility.\n'
            f'{note}'
            '# Do not edit by hand -- rerun the script instead.\n\n'
        )
        for tech, value in f_mult.items():
            value = float(value)
            value = 0.0 if value <= _ZERO_THR else value + _EPS
            f.write(f"let f_max['{tech}'] := {value!r};\n")

    print(f'  wrote {len(f_mult)} f_max overrides -> {out_path}')


def main(validation_2021: str = 'QC_validation_2021.dat',
         validation_2023: str = 'QC_validation_2023.dat'):
    """Output filename is '<validation_dat_stem>_f_max.dat', matching how generate_dat_files.py looks it up."""
    print(f'Running 2021 validation snapshot ({validation_2021}) ...')
    f_mult_2020 = _f_mult(run_model(_build_base_model(validation_2021)))

    print(f'Running 2023 validation snapshot ({validation_2023}) ...')
    f_mult_2025 = _f_mult(run_model(_build_base_model(validation_2023)))

    # Floor 2025 to 2020 for any technology where the raw 2025 value is lower.
    common = f_mult_2025.index.intersection(f_mult_2020.index)
    floored = common[f_mult_2025.loc[common] < f_mult_2020.loc[common]]
    if len(floored) > 0:
        print(f'  flooring {len(floored)} technologies to their 2020 value: {list(floored)}')
        f_mult_2025.loc[floored] = f_mult_2020.loc[floored]

    _write_f_max_file(f_mult_2020, _SNAPSHOT_DIR / f'{Path(validation_2021).stem}_f_max.dat', '2021')
    _write_f_max_file(
        f_mult_2025, _SNAPSHOT_DIR / f'{Path(validation_2023).stem}_f_max.dat', '2023',
        note='# Floored to the 2020 value for technologies where 2025 would otherwise be lower.\n',
    )


if __name__ == '__main__':
    main()
