"""Assemble the long-format recycling-rate table and write
ampl_files/Material_recycling.dat -- recycling-rate counterpart to
mi_pipeline/build_table.py.

Every technology in Recycling_rates.xlsx's Mapping sheet is recomputed on
every run: techs with a real mapping_type get recycling_rate from the
literature source data (currently only the 160 private-mobility ones, see
sources.load_rr_vehicles), techs marked not_mapped get skipped (AMPL default
0 applies). Only `recycling_rate` is written here -- `collection_rate` has no
source data yet (no sheet in the workbook), and `recycling_cost` /
`disposal_cost` / `recycling_gwp` / `disposal_gwp` never come from this
workbook at all; those stay in the hand-maintained
ampl_files/Material_recycling_fixture.dat (loaded alongside this file by
run_pathway_materials.py), same reasoning as Material_limits.dat being kept
separate from the regenerated Material_intensity.dat.
"""
import time
from pathlib import Path

import pandas as pd

from mi_pipeline import canonical
from mi_pipeline.mapping import load_mapping

from . import sources
from .aggregate import YEARS, compute_all

_PROJ_ROOT = Path(__file__).resolve().parents[2]  # .../projects/critical_materials
OUT_DAT_PATH = _PROJ_ROOT / 'ampl_files' / 'Material_recycling.dat'


def _mapped_rows(mapping, rates):
    """Long-format (tech, material, year, value, comment) rows for every
    technology in the Mapping sheet (in scope). not_mapped techs contribute
    nothing (NaN cells, skipped when writing)."""
    rows = []
    for tech, row in mapping.iterrows():
        df = rates[tech]
        if row['mapping_type'] == 'not_mapped':
            continue
        subtechs = ','.join(row['subtechs'])
        confidence_tag = f"[{row['confidence']}] " if row['confidence'] else ''
        comment = f"{confidence_tag}mapping: {row['mapping_type']} <- {subtechs}. See the Mapping sheet."
        for material in df.index:
            for year in YEARS:
                raw_value = df.loc[material, year]
                if pd.isna(raw_value):
                    continue
                rows.append((year, tech, material, float(raw_value), comment))
    return rows


def _write_dat(rows, path=OUT_DAT_PATH):
    """`let recycling_rate['YEAR_XXXX','TECH','MAT'] := value ; # comment` lines
    only -- no `set MATERIALS := ...;` header, since Material_intensity.dat
    (loaded earlier in run_pathway_materials.py's file list) already declares
    it and AMPL sets shouldn't be redeclared."""
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write("data;\n\n")
        f.write("# Auto-generated by rr_pipeline (run_build_rr.py) from Recycling_rates.xlsx -- do not hand-edit.\n")
        f.write("# collection_rate / recycling_cost / disposal_cost / recycling_gwp / disposal_gwp are NOT\n")
        f.write("# written here (no source data yet) -- see Material_recycling_fixture.dat.\n\n")
        for year, tech, material, value, comment in rows:
            f.write(f"let recycling_rate['{year}','{tech}','{material}'] := {value} ; # [-] {comment}\n")
    return path


def build(scenario='baseline', write_dat=True):
    t0 = time.time()
    mapping = load_mapping(path=sources.SOURCE_XLSX)

    # Same not-yet-in-QC_data.dat filtering as mi_pipeline.build_table.build.
    canonical_techs = set(canonical.all_target_techs())
    claims_real_data = mapping['mapping_type'] != 'not_mapped'
    not_yet_modeled = set(mapping.index[claims_real_data]) - canonical_techs
    if not_yet_modeled:
        print(f"[rr_build_table] skipping (not yet in QC_data.dat): {sorted(not_yet_modeled)}")
    mapped_scope = set(mapping.index) - not_yet_modeled
    mapping = mapping.loc[sorted(mapped_scope)]

    rates = compute_all(scenario=scenario)
    print(f"[rr_build_table] computed {len(rates)} tech recycling rates in {time.time()-t0:.1f}s")

    rows = _mapped_rows(mapping, rates)
    print(f"[rr_build_table] built {len(rows)} rows for {len(mapping)} technologies in {time.time()-t0:.1f}s")

    if write_dat:
        out_path = _write_dat(rows)
        print(f"[rr_build_table] wrote {out_path.name} ({len(rows)} lines) in {time.time()-t0:.1f}s")

    print(f"[rr_build_table] total: {time.time()-t0:.1f}s")
    return rows


if __name__ == '__main__':
    build()
