"""Assemble the long-format recycling-rate table and write
ampl_files/Material_recycling.dat -- recycling-rate counterpart to
mi_pipeline/build_table.py.

Every technology in Recycling_rates.xlsx's Mapping sheet is recomputed on
every run: techs with a real mapping_type get recycling_rate from the
literature source data (currently only the 160 private-mobility ones, see
sources.load_rr_vehicles), techs marked not_mapped get skipped (AMPL default
0 applies). A single simple recycling_rate per (tech, material) -- plus
recycling_scenario_share (the recycled_material_scenario equality's target,
from the Recycling_scenario sheet, clipped to each material's actual
achievable rate, see _max_achievable_rate). `collection_rate` has no source
data yet (no sheet in the workbook), and `recycling_cost` / `disposal_cost` /
`recycling_gwp` / `disposal_gwp` never come from this workbook at all -- none
of them are written here, so they stay at their AMPL defaults
(collection_rate=1, everything else=0) unless a future source sheet is added
and this module is extended to cover them.
"""
import time
from pathlib import Path

import pandas as pd

from mi_pipeline import canonical
from mi_pipeline.mapping import load_mapping

from . import sources
from .aggregate import YEARS, compute_all

_PROJ_ROOT = Path(__file__).resolve().parents[2]  # .../projects/critical_materials
OUT_DAT_PATH = _PROJ_ROOT / 'ampl_files' / 'Material_recycling.dat'


def _mapped_rows(mapping, rates):
    """Long-format (tech, material, year, value, comment) rows for every
    technology in the Mapping sheet (in scope). not_mapped techs contribute
    nothing (NaN cells, skipped when writing)."""
    rows = []
    for tech, row in mapping.iterrows():
        df = rates[tech]
        if row['mapping_type'] == 'not_mapped':
            continue
        subtechs = ','.join(row['subtechs'])
        confidence_tag = f"[{row['confidence']}] " if row['confidence'] else ''
        comment = f"{confidence_tag}mapping: {row['mapping_type']} <- {subtechs}. See the Mapping sheet."
        for material in df.index:
            for year in YEARS:
                raw_value = df.loc[material, year]
                if pd.isna(raw_value):
                    continue
                rows.append((year, tech, material, float(raw_value), comment))
    return rows


def _max_achievable_rate(mapped_rows):
    """{(year, material): max recycling_rate across technologies} -- the
    aggregate value recycled_material_scenario can hit exactly (a weighted average
    across technologies can never exceed the best technology's own rate), used
    to clip recycling_scenario_share below so follow_scenario=True can't force
    an infeasible floor on materials with little or no RR_ data."""
    best = {}
    for year, _tech, material, value, _comment in mapped_rows:
        key = (year, material)
        if value > best.get(key, 0.0):
            best[key] = value
    return best


def _scenario_rows(scenario_df, max_rate_by_year_mat):
    """Long-format (year, material, value) rows for recycling_scenario_share,
    from the Recycling_scenario sheet -- only the years actually present as
    columns (2025..2050 today, no 2020). Clipped to max_rate_by_year_mat[year,
    material] (0 if the material has no RR_ data at all for that year) --
    the raw sheet is dummy placeholder values applied uniformly to every
    material, most of which have no real recycling_rate to back them up."""
    rows = []
    for material in scenario_df.index:
        for year_int in scenario_df.columns:
            raw_value = scenario_df.loc[material, year_int]
            if pd.isna(raw_value):
                continue
            year = f'YEAR_{year_int}'
            ceiling = max_rate_by_year_mat.get((year, material), 0.0)
            value = min(float(raw_value), ceiling)
            if value < raw_value:
                print(f"[rr_build_table] clipping recycling_scenario_share[{year},{material}] "
                      f"{raw_value} -> {value} (max achievable recycling_rate)")
            rows.append((year, material, value))
    return rows


def _write_dat(rows, scenario_rows, path=OUT_DAT_PATH):
    """`let recycling_rate['YEAR_XXXX','TECH','MAT'] := value ; # comment` and
    `let recycling_scenario_share['YEAR_XXXX','MAT'] := value ;` lines -- no
    `set MATERIALS := ...;` header, since Material_intensity.dat (loaded
    earlier in run_pathway_materials.py's file list) already declares it and
    AMPL sets shouldn't be redeclared."""
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write("data;\n\n")
        f.write("# Auto-generated by rr_pipeline (run_build_rr.py) from Recycling_rates.xlsx -- do not hand-edit.\n")
        f.write("# collection_rate / recycling_cost / disposal_cost / recycling_gwp / disposal_gwp are NOT\n")
        f.write("# written here (no source data yet) -- AMPL defaults apply (collection_rate=1, rest=0).\n\n")
        for year, tech, material, value, comment in rows:
            f.write(f"let recycling_rate['{year}','{tech}','{material}'] := {value} ; # [-] {comment}\n")
        f.write("\n# recycled_material_scenario's target when follow_scenario=1 (Recycling_scenario sheet).\n")
        for year, material, value in scenario_rows:
            f.write(f"let recycling_scenario_share['{year}','{material}'] := {value} ; # [-]\n")
    return path


def build(scenario='baseline', write_dat=True):
    t0 = time.time()
    mapping = load_mapping(path=sources.SOURCE_XLSX)

    # Same not-yet-in-QC_data.dat filtering as mi_pipeline.build_table.build.
    canonical_techs = set(canonical.all_target_techs())
    claims_real_data = mapping['mapping_type'] != 'not_mapped'
    not_yet_modeled = set(mapping.index[claims_real_data]) - canonical_techs
    if not_yet_modeled:
        print(f"[rr_build_table] skipping (not yet in QC_data.dat): {sorted(not_yet_modeled)}")
    mapped_scope = set(mapping.index) - not_yet_modeled
    mapping = mapping.loc[sorted(mapped_scope)]

    rates = compute_all(scenario=scenario)
    print(f"[rr_build_table] computed {len(rates)} tech recycling rates in {time.time()-t0:.1f}s")

    rows = _mapped_rows(mapping, rates)
    print(f"[rr_build_table] built {len(rows)} rows for {len(mapping)} technologies in {time.time()-t0:.1f}s")

    max_rate_by_year_mat = _max_achievable_rate(rows)
    scenario_df = sources.load_recycling_scenario()
    scenario_rows = _scenario_rows(scenario_df, max_rate_by_year_mat)
    print(f"[rr_build_table] built {len(scenario_rows)} recycling_scenario_share rows in {time.time()-t0:.1f}s")

    if write_dat:
        out_path = _write_dat(rows, scenario_rows)
        print(f"[rr_build_table] wrote {out_path.name} ({len(rows) + len(scenario_rows)} lines) in {time.time()-t0:.1f}s")

    print(f"[rr_build_table] total: {time.time()-t0:.1f}s")
    return rows


if __name__ == '__main__':
    build()
